<<: !include ./secrets.yaml

esphome:
  name: esp8266test
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: $wifi_ssid
  password: $wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: $fallback_ssid
    password: $fallback_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: $api_password

ota:
  password: $ota_password

switch:
  - platform: gpio
    name: "LED"
    pin: 0
